version: '3.4'
services:
  dotnet:
    container_name: dses-demo-app-chsarp
    image: eusdsesregistry.azurecr.io/dses-demo-app-csharp
    build:
      context: .
      target: final
    ports:
      - 80:80
