parameters:
  pool:
    vmImage: 'vs2017-win2016'
  serviceName: ''
  projectName: ''
  teamName: ''
  preset: 'ASA-SDLC'
  incrementalScan: false
  synchronise: true
  folderExclusion: 'cvs, .svn, .hg , .git, .bzr, bin , obj,  backup, .idea'
  fileExtension: '!*.DS_Store,!*.ipr,!*.iws,!*.bak,!*.tmp,!*.aac,!*.aif,!*.iff,!*.m3u,!*.mid,!*.mp3,!*.mpa,!*.ra,!*.wav,!*.wma,!*.3g2,!*.3gp,!*.asf,!*.asx,!*.avi,!*.flv,!*.mov,!*.mp4,!*.mpg,!*.rm,!*.swf,!*.vob,!*.wmv,!*.bmp,!*.gif,!*.jpg,!*.png,!*.psd,!*.tif,!*.swf,!*.jar,!*.zip,!*.rar,!*.exe,!*.dll,!*.pdb,!*.7z,!*.gz,!*.tar.gz,!*.tar,!*.gz,!*.ahtm,!*.ahtml,!*.fhtml,!*.hdm,!*.hdml,!*.hsql,!*.ht,!*.hta,!*.htc,!*.htd,!*.war,!*.ear,!*.htmls,!*.ihtml,!*.mht,!*.mhtm,!*.mhtml,!*.ssi,!*.stm,!*.stml,!*.ttml,!*.txn,!*.xhtm,!*.xhtml,!*.class,!*.iml'
  scanTimeout: ''
  denyProjectCreation: false
  vulnerabilityThreshold: false
  thresholdHigh: ''
  thresholdMedium: ''
  thresholdLow: ''
  osaEnabled: false
  osaFolderExclusion: ''
  osaArchiveInclude: '*.zip, *.war, *.ear, *.tgz'
  osaVulnerabilityThreshold: false
  osaVulnerabilityThresholdHigh: ''
  osaVulnerabilityThresholdMedium: ''
  osaVulnerabilityThresholdLow: ''
  targetBranch: 'refs/heads/master'

stages:
  - stage: SastStage
    displayName: 'SAST Checkmarx Scan'
    dependsOn: 'TruffleHog'
    jobs:
    - template: ../jobs/checkmarx-job.yml
      parameters:
        pool: '${{ parameters.pool }}'
        serviceName: '${{ parameters.serviceName }}'
        projectName: '${{ parameters.projectName }}'
        teamName: '${{ parameters.teamName }}'
        preset: '${{ parameters.preset }}'
        incrementalScan: '${{ parameters.incrementalScan }}'
        synchronise: '${{ parameters.synchronise }}'
        folderExclusion: '${{ parameters.folderExclusion }}'
        fileExtension: '${{ parameters.fileExtension }}'
        scanTimeout: '${{ parameters.scanTimeout }}'
        denyProjectCreation: '${{ parameters.denyProjectCreation }}'
        vulnerabilityThreshold: '${{ parameters.vulnerabilityThreshold }}'
        thresholdHigh: '${{ parameters.thresholdHigh }}'
        thresholdMedium: '${{ parameters.thresholdMedium }}'
        thresholdLow: '${{ parameters.thresholdLow }}'
        osaEnabled: '${{ parameters.osaEnabled }}'
        osaFolderExclusion: '${{ parameters.osaFolderExclusion }}'
        osaArchiveInclude: '${{ parameters.osaArchiveInclude }}'
        osaVulnerabilityThreshold: '${{ parameters.osaVulnerabilityThreshold }}'
        osaVulnerabilityThresholdHigh: '${{ parameters.osaVulnerabilityThresholdHigh }}'
        osaVulnerabilityThresholdMedium: '${{ parameters.osaVulnerabilityThresholdMedium }}'
        osaVulnerabilityThresholdLow: '${{ parameters.osaVulnerabilityThresholdLow }}'
        targetBranch: '${{ parameters.targetBranch }}'
